#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# routes.yaml

app_decrease_duration:
    path: /decrease-duration
    controller: App\Controller\DecreaseDurationController::decreaseDurationAction